name: Test SSH Connection Staging

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER2_PORT }} -H ${{ secrets.SERVER2_HOST }} >> ~/.ssh/known_hosts

      - name: Probar conexión SSH
        run: |
          echo "🔍 Probando conexión a ${{ secrets.SERVER2_USER }}@${{ secrets.SERVER2_HOST }}:${{ secrets.SERVER2_PORT }}..."
          ssh -p ${{ secrets.SERVER2_PORT }} -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER2_USER }}@${{ secrets.SERVER2_HOST }} "echo '✅ Conexión SSH exitosa en STAGING: $(hostname)'; exit"

      - name: Confirmación final
        run: echo "✅ Test SSH completado con éxito"
